apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-candidate
spec:
  selector:
    matchLabels:
      app: candidate
  replicas: 2
  template:
    metadata:
      labels:
        app: candidate
    spec:
      containers:
        - name: candidate
          image: namrahov/candidate-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: candidate-k8ssvc
spec:
  type: NodePort
  selector:
    app: candidate
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
