apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: candidate
  replicas: 1
  template:
    metadata:
      labels:
        app: candidate
    spec:
      containers:
        - name: candidate
          image: namrahov/candidate-image:latest

---
apiVersion: v1
kind: Service
metadata:
  name: candidate

spec:
  selector:
    app: candidate

  ports:
    - name: http
      port: 8080

  type: LoadBalancer
