apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-candidate
spec:
  selector:
    matchLabels:
      app: candidate
  replicas: 1
  template:
    metadata:
      labels:
        app: candidate
    spec:
      containers:
        - name: candidate
          image: ${REPOSITORY_TAG}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-candidate
spec:
  selector:
    app: candidate
  ports:
    - name: http
      port: 8080
  type: LoadBalancer
